name: build conan package
on: push
jobs:
  build_conan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # install dependencies
      - name: dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq python3 python3-pip python3-setuptools build-essential cmake make
          sudo pip3 install conan
      # build project
      - name: build conan package
        run: |
          conan profile new default --detect --force # Generates default profile detecting GCC and sets old ABI
          conan profile update settings.compiler.libcxx=libstdc++11 default  # Sets libcxx to C++11 ABI
          conan create .